Import('env', 'include_path', 'libs_path','extraLibPaths', 'commonLibs','commonDefines','commonCFlags','commonLFlags')
# toolkit.h is located in this directory, add it to the include path
lEnv = env.Clone()
lEnv.Append(CPPPATH=include_path)

includeLibs = ['linkedlistLib']
libsPaths = list()
for lib in includeLibs:
	newLib = '{libpath}/{lib}'.format(libpath=libs_path, lib=lib)
	print("Libpath > Added Lib >> " + newLib)
	libsPaths.append(newLib)
libsPaths.extend(extraLibPaths)
includeLibs.extend(commonLibs)
lEnv.Append(LIBPATH=libsPaths)
lEnv.Append(LIBS=includeLibs)
lEnv.Append(CPPDEFINES=commonDefines)
lEnv.Append(CCFLAGS=commonCFlags)
lEnv.Append(LINKFLAGS=commonLFlags)

# Let's declare a library named toolkit, using toolkit.c as its only source
lEnv.Program('linkedList', ['main.cpp'])
